import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // Route infrastructure: `lazyPage` is a factory that *returns* a component, so the
    // file exports a non-component while defining components. `extraHOCs` does not cover
    // this — it whitelists calls to a HOC, not exporting the factory itself. Nothing here
    // renders user-visible state worth hot-reloading, so the check is off for this file
    // only rather than for the app.
    files: ['src/app/lazy-page.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    // shadcn primitives are generated by `shadcn add` and re-generated on upgrade. They
    // export a component alongside its cva variants, which react-refresh objects to;
    // splitting them by hand would be undone by the next regeneration.
    files: ['src/components/ui/**/*.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
